.class public Lcom/microsoft/appcenter/crashes/model/TestCrashException;
.super Ljava/lang/RuntimeException;
.source "TestCrashException.java"


# static fields
.field static final CRASH_MESSAGE:Ljava/lang/String; = "Test crash exception generated by SDK"
    .annotation build Landroid/support/annotation/VisibleForTesting;
    .end annotation
.end field


# direct methods
.method public constructor <init>()V
    .locals 3

    .prologue
    .line 22
    move-object v0, p0

    .local v0, "this":Lcom/microsoft/appcenter/crashes/model/TestCrashException;
    move-object v1, v0

    const-string/jumbo v2, "Test crash exception generated by SDK"

    invoke-direct {v1, v2}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    .line 23
    return-void
.end method
